name: Build
on: [push, pull_request]

jobs:
  build_ndbcli:
    name: ndb-cli
    runs-on: ubuntu-latest
    container: 
      image: docker.io/golang:1.14
      env: 
        GOOS: linux
        GOARCH: arm
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        cd ./ndb-cli/
        go build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: ndb-cli
        path: ./ndb-cli/ndb-cli

  build_libndb:
    name: libndb
    needs: build_ndbcli
    runs-on: ubuntu-latest
    container: docker.io/geek1011/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Download ndb-cli
      uses: actions/download-artifact@v2
      with:
        name: ndb-cli
        path: ./ndb-cli
    - name: Set executable bit on ndb-cli
      run: chmod +x ./ndb-cli/ndb-cli
    - name: Build
      run: make all
    - name: KoboRoot with ndb-cli
      run: make koboroot
    - name: Upload KoboRoot with ndb-cli
      uses: actions/upload-artifact@v2
      with:
        name: NickelDBus-with-cli
        path: KoboRoot.tgz
    - name: KoboRoot library only
      run: make koborootlib
    - name: Upload KoboRoot library only
      uses: actions/upload-artifact@v2
      with:
        name: NickelDBus-lib-only
        path: KoboRoot.tgz
  