name: Build
on: [push, pull_request]

jobs:
  build_ndb:
    name: ndb
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: make clean && make all cli koboroot
    - name: Build Documentation
      run: make doc
    - name: Upload KoboRoot with 'qndb'
      uses: actions/upload-artifact@v4
      with:
        name: NickelDBus
        path: KoboRoot.tgz
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: Documentation
        path: ./qdoc/html
  