name: Build
on: [push, pull_request]

jobs:
  build_ndb:
    name: ndb
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make clean && make && make cli
    - name: KoboRoot with 'qndb'
      run: make koboroot
    - name: Upload KoboRoot with 'qndb'
      uses: actions/upload-artifact@v2
      with:
        name: NickelDBus
        path: KoboRoot.tgz
  