name: Documentation
on:
  push:
    tags:
    - "*"
jobs:
  build_doc:
    name: ndb_doc
    runs-on: ubuntu-latest
    container: docker.io/geek1011/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make doc
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./qdoc/html
  