name: Create Release
on:
  push:
    tags:
    - "*"
jobs:
  build_ndb:
    name: ndb
    runs-on: ubuntu-latest
    container: ghcr.io/pgaskin/nickeltc:1.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: make clean && make && make cli
    - name: Create KoboRoot.tgz archive
      run: make koboroot
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        body: '<!-- replace this with the release notes -->'
        files: |
          KoboRoot.tgz
        token: ${{ secrets.GITHUB_TOKEN }}
    